language: python
python:
  - "3.6"
# command to install dependencies
install:
  - cd qa
  - pip install -r requirements.txt
  - python -m spacy download en
  - python -m nltk.downloader all
  - python -m spacy download en_core_web_lg
# command to run tests
script:
  - python setup.py test