language: python
python:
  - "3.6"
# command to install dependencies
install:
  - cd qa
  - pip install -r requirements.txt
  - pip install http://download.pytorch.org/whl/cu80/torch-0.3.1-cp36-cp36m-linux_x86_64.whl
  - pip install torchvision
  - python -m spacy download en > /dev/null
  - python -m nltk.downloader all > /dev/null
  - python -m spacy download en_core_web_lg > /dev/null
# command to run tests
script:
  - python setup.py test